### ISSUE TITLE
Problem with --help

### ISSUE THREAD

**Issue by sinamajidian** [dcdanko/minerva_barcode_deconvolution#9]
Hi

After installation using the below line
```pip install minerva_deconvolve --user```
I run this 
``` minerva_deconvolve --help```

I faced this
```majid001@eddy:~/Install/minerva$ minerva_deconvolve --help
Traceback (most recent call last):
  File "/home/majid001/.local/bin/minerva_deconvolve", line 6, in <module>
    from minerva.deconvolution.deconvolve_barcodes import main
  File "/home/majid001/.local/lib/python2.7/site-packages/minerva/deconvolution/deconvolve_barcodes.py", line 27
    print(msg.format(len(barcodeTables)), file=sys.stderr)
                                              ^
SyntaxError: invalid syntax
```

Would you please help me on this issue?

**Comment by dcdanko** [comment]
My guess is that you're using `python 2.7`, minerva is written for `python 3.x`
